### ISSUE TITLE
Errors opening data from Bruker instruments

### ISSUE THREAD

**Issue by jbellamycarter** [jbellamycarter/pepfoot#2]
Importing `.mz5` converted from Bruker instruments (via .mzXML intermediate) fails with an error like so:

```python
Traceback (most recent call last):
File "pepFoot\pepFootGui.py", line 848, in update_PepList
File "pepFoot\pepFootGui.py", line 314, in wrapper
File "pepFoot\pepFootGui.py", line 776, in file_import
File "pepFoot\pepFootGui.py", line 785, in open_mz5
File "pepFoot\mz5Reader.py", line 61, in __init__
File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
File "site-packages\h5py\_hl\group.py", line 177, in __getitem__
File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
File "h5py\h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'ChromatogramIndex' doesn't exist)"
```

This is caused by Bruker data files lacking a discrete total ion chromatogram, which is required to generate `ChromatogramIndex` and related structures in `.mz5` files. PepFoot uses this entry to determine the number of scans in the data file, which are subsequently used for filling a lookup table.

**Comment by jbellamycarter** [comment]
**Proposed fix**:  Change the scan counting to use `SpectrumMetaData` or `SpectrumIndex` instead.

**Comment by jbellamycarter** [comment]
Fix implemented, Bruker data now import successfully from `.mz5` files.
